# Generated by Django 4.1.4 on 2022-12-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('player1', models.CharField(max_length=50)),
                ('player2', models.CharField(max_length=50)),
                ('player1_id', models.IntegerField()),
                ('player2_id', models.IntegerField()),
                ('game_state', models.CharField(max_length=50)),
                ('player1_side', models.CharField(max_length=50)),
                ('player2_side', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Gameuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('draws', models.IntegerField()),
                ('Games', models.ManyToManyField(to='gameuser.game')),
            ],
        ),
    ]
