# Generated by Django 3.1.3 on 2022-12-22 06:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gameuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gamestate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pos00', models.CharField(default=' ', max_length=1)),
                ('pos01', models.CharField(default=' ', max_length=1)),
                ('pos02', models.CharField(default=' ', max_length=1)),
                ('pos10', models.CharField(default=' ', max_length=1)),
                ('pos11', models.CharField(default=' ', max_length=1)),
                ('pos12', models.CharField(default=' ', max_length=1)),
                ('pos20', models.CharField(default=' ', max_length=1)),
                ('pos21', models.CharField(default=' ', max_length=1)),
                ('pos22', models.CharField(default=' ', max_length=1)),
                ('gameid', models.IntegerField(default=-1)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player2',
        ),
        migrations.RemoveField(
            model_name='gameuser',
            name='Games',
        ),
        migrations.AddField(
            model_name='game',
            name='current_player',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='game',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='game',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='game',
            name='started_by',
            field=models.CharField(default='player1', max_length=50),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_state',
            field=models.CharField(default='in progress', max_length=50),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='game',
            name='player1_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='game',
            name='player1_side',
            field=models.CharField(default='X', max_length=50),
        ),
        migrations.AlterField(
            model_name='game',
            name='player2_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='game',
            name='player2_side',
            field=models.CharField(default='O', max_length=50),
        ),
        migrations.AlterField(
            model_name='gameuser',
            name='draws',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gameuser',
            name='email',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='gameuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gameuser',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gameuser',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='gameuser',
            name='username',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='gameuser',
            name='wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='gamestatus',
            field=models.ManyToManyField(to='gameuser.Gamestate'),
        ),
    ]
