# Generated by Django 3.1.3 on 2022-12-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameuser', '0002_auto_20221222_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameuser',
            name='Games',
            field=models.ManyToManyField(to='gameuser.Game'),
        ),
    ]
