# Generated by Django 3.1.3 on 2022-12-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameuser', '0003_gameuser_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameuser',
            name='email',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='gameuser',
            name='password',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='gameuser',
            name='username',
            field=models.CharField(default='', max_length=200),
        ),
    ]
