# Generated by Django 3.1.3 on 2022-12-22 07:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gameuser', '0005_auto_20221222_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameuser',
            name='token',
            field=models.CharField(default=uuid.uuid4, max_length=200),
        ),
    ]
