# Generated by Django 3.1.3 on 2022-12-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameuser', '0006_gameuser_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_over',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='gameid',
            field=models.CharField(default='', max_length=50),
        ),
    ]
